/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/environment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Identifica o ambiente e sua fonte selecionada */
        get: operations["get_environment_api_v1_environment_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista jobs persistidos */
        get: operations["list_jobs_api_v1_jobs_get"];
        put?: never;
        /** Enfileira uma coleta tipada */
        post: operations["create_job_api_v1_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consulta o estado e progresso de um job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancela ou solicita o cancelamento cooperativo */
        post: operations["cancel_job_api_v1_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/continue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Continua uma coleta parcial que atingiu o orçamento */
        post: operations["continue_job_api_v1_jobs__job_id__continue_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/restart-scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inicia nova varredura após invalidação do cursor */
        post: operations["restart_scan_api_v1_jobs__job_id__restart_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retoma um job falho ou cancelado */
        post: operations["resume_job_api_v1_jobs__job_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista presets e sua disponibilidade neste ambiente */
        get: operations["get_presets_api_v1_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/processes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pesquisa processos persistidos */
        get: operations["list_processes_api_v1_processes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/processes/{process_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consulta um processo local */
        get: operations["get_process_api_v1_processes__process_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/processes/{process_id}/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista movimentos normalizados sem misturar representações */
        get: operations["list_movements_api_v1_processes__process_id__movements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/processes/{process_id}/representations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista representações e seus diagnósticos */
        get: operations["list_representations_api_v1_processes__process_id__representations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DiscoveryCriteria */
        DiscoveryCriteria: {
            /** Filed From */
            filed_from?: string | null;
            /** Filed Through */
            filed_through?: string | null;
            /**
             * Hit Budget
             * @default 2000
             */
            hit_budget: number;
            /**
             * Page Size
             * @default 100
             */
            page_size: number;
            /** Preset Id */
            preset_id: string;
        };
        /** DiscoveryJobRequest */
        DiscoveryJobRequest: {
            criteria: components["schemas"]["DiscoveryCriteria"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "discovery";
        };
        /** EnvironmentResponse */
        EnvironmentResponse: {
            /**
             * Environment
             * @enum {string}
             */
            environment: "demo" | "real" | "test";
            /**
             * Source
             * @enum {string}
             */
            source: "synthetic" | "datajud";
            /** Source Disabled Reason */
            source_disabled_reason: string | null;
            /** Source Enabled */
            source_enabled: boolean;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Details */
            details?: components["schemas"]["ErrorDetail"][] | {
                [key: string]: unknown;
            } | null;
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Location */
            location: (string | number)[];
            /** Message */
            message: string;
            /** Type */
            type: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** EvidenceResponse */
        EvidenceResponse: {
            /** Evidence Ids */
            evidence_ids: string[];
            /** Reason */
            reason: string;
            /**
             * State
             * @enum {string}
             */
            state: "validated" | "incompatible" | "inconclusive";
        };
        /** JobAttemptResponse */
        JobAttemptResponse: {
            /** Attempt Number */
            attempt_number: number;
            /** Error Code */
            error_code: string | null;
            /** Error Summary */
            error_summary: string | null;
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Outcome */
            outcome: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
        };
        /** JobCheckpointResponse */
        JobCheckpointResponse: {
            /** Next Page */
            next_page: number;
            /** Revision */
            revision: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** JobCommandResponse */
        JobCommandResponse: {
            /**
             * Cancel Requested
             * @default false
             */
            cancel_requested: boolean;
            /**
             * Collection Id
             * Format: uuid
             */
            collection_id: string;
            /**
             * Cursor Invalid
             * @default false
             */
            cursor_invalid: boolean;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Reused
             * @default false
             */
            reused: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "retry_wait" | "completed" | "partial" | "failed" | "cancelled";
        };
        /** JobCreatedResponse */
        JobCreatedResponse: {
            /**
             * Collection Id
             * Format: uuid
             */
            collection_id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Reused */
            reused: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "retry_wait" | "completed" | "partial" | "failed" | "cancelled";
        };
        /** JobDetailResponse */
        JobDetailResponse: {
            /** Attempt Count */
            attempt_count: number;
            /** Attempts */
            attempts: components["schemas"]["JobAttemptResponse"][];
            /** Cancel Requested */
            cancel_requested: boolean;
            checkpoint: components["schemas"]["JobCheckpointResponse"];
            /**
             * Collection Id
             * Format: uuid
             */
            collection_id: string;
            /** Coverage */
            coverage: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Criteria */
            criteria: {
                [key: string]: unknown;
            };
            /** Cursor Invalid */
            cursor_invalid: boolean;
            /**
             * Environment
             * @enum {string}
             */
            environment: "demo" | "real";
            /** Events */
            events: components["schemas"]["JobEventResponse"][];
            /** Execution */
            execution: {
                [key: string]: unknown;
            };
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "discovery" | "refresh_number";
            /**
             * Next Attempt At
             * Format: date-time
             */
            next_attempt_at: string;
            /** Predecessor Job Id */
            predecessor_job_id: string | null;
            /** Reason */
            reason: string | null;
            /** Retry Cycle */
            retry_cycle: number;
            /** Source */
            source: string;
            /** Started At */
            started_at: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "retry_wait" | "completed" | "partial" | "failed" | "cancelled";
            /** Tribunal */
            tribunal: string;
        };
        /** JobEventResponse */
        JobEventResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /** Event Number */
            event_number: number;
            /** Event Type */
            event_type: string;
        };
        /** JobSummaryResponse */
        JobSummaryResponse: {
            /** Attempt Count */
            attempt_count: number;
            /** Cancel Requested */
            cancel_requested: boolean;
            /**
             * Collection Id
             * Format: uuid
             */
            collection_id: string;
            /** Coverage */
            coverage: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Environment
             * @enum {string}
             */
            environment: "demo" | "real";
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "discovery" | "refresh_number";
            /**
             * Next Attempt At
             * Format: date-time
             */
            next_attempt_at: string;
            /** Reason */
            reason: string | null;
            /** Retry Cycle */
            retry_cycle: number;
            /** Source */
            source: string;
            /** Started At */
            started_at: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "retry_wait" | "completed" | "partial" | "failed" | "cancelled";
            /** Tribunal */
            tribunal: string;
        };
        /** LatestCollectionResponse */
        LatestCollectionResponse: {
            /**
             * Capture Outcome
             * @enum {string}
             */
            capture_outcome: "new" | "updated" | "unchanged";
            /**
             * Collection Id
             * Format: uuid
             */
            collection_id: string;
            /**
             * Environment
             * @enum {string}
             */
            environment: "demo" | "real";
            /**
             * Included At
             * Format: date-time
             */
            included_at: string;
            /** Job Id */
            job_id: string | null;
            /** Job Status */
            job_status: ("queued" | "running" | "retry_wait" | "completed" | "partial" | "failed" | "cancelled") | null;
        };
        /** LiveResponse */
        LiveResponse: {
            /**
             * Status
             * @default live
             * @constant
             */
            status: "live";
        };
        /** MovementDiagnosticResponse */
        MovementDiagnosticResponse: {
            /** Available */
            available: boolean;
            /** Is Complete */
            is_complete: boolean | null;
            /** Normalizer Version */
            normalizer_version: string | null;
            /** Processed At */
            processed_at: string | null;
            /** Rejection Count */
            rejection_count: number | null;
            /**
             * Representation Id
             * Format: uuid
             */
            representation_id: string;
        };
        /** PaginationResponse[JobSummaryResponse] */
        PaginationResponse_JobSummaryResponse_: {
            /** Items */
            items: components["schemas"]["JobSummaryResponse"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** PaginationResponse[ProcessRepresentationResponse] */
        PaginationResponse_ProcessRepresentationResponse_: {
            /** Items */
            items: components["schemas"]["ProcessRepresentationResponse"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** PaginationResponse[ProcessSummaryResponse] */
        PaginationResponse_ProcessSummaryResponse_: {
            /** Items */
            items: components["schemas"]["ProcessSummaryResponse"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** PresetAvailabilityResponse */
        PresetAvailabilityResponse: {
            /** Enabled */
            enabled: boolean;
            /**
             * Environment
             * @enum {string}
             */
            environment: "demo" | "real";
            /** Label */
            label: string;
            /** Reasons */
            reasons: string[];
        };
        /** PresetResponse */
        PresetResponse: {
            availability: components["schemas"]["PresetAvailabilityResponse"];
            /** Capture Explanation */
            capture_explanation: string;
            /** Evidence */
            evidence: {
                [key: string]: components["schemas"]["EvidenceResponse"];
            };
            /** Family */
            family: string;
            /** Filters */
            filters: {
                [key: string]: number[];
            };
            /** Id */
            id: string;
            /** Include Descendants */
            include_descendants: boolean;
            /** Justification */
            justification: string;
            /** Name */
            name: string;
            /** Purpose */
            purpose: string;
            /** Required For Real */
            required_for_real: string[];
            /** Rural Link Status */
            rural_link_status: string;
            /** Version */
            version: string;
        };
        /** PresetsResponse */
        PresetsResponse: {
            /**
             * Environment
             * @enum {string}
             */
            environment: "demo" | "real";
            /** Items */
            items: components["schemas"]["PresetResponse"][];
        };
        /** ProcessDetailResponse */
        ProcessDetailResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            latest_collection: components["schemas"]["LatestCollectionResponse"] | null;
            /** Latest Observed At */
            latest_observed_at: string | null;
            /** Numero Cnj */
            numero_cnj: string;
            /** Representation Count */
            representation_count: number;
        };
        /** ProcessMovementResponse */
        ProcessMovementResponse: {
            /** Comparison Detail */
            comparison_detail: {
                [key: string]: unknown;
            } | null;
            /** Comparison Result */
            comparison_result: string;
            /** Content */
            content: {
                [key: string]: unknown;
            };
            /**
             * First Observed At
             * Format: date-time
             */
            first_observed_at: string;
            /** Multiplicity Ordinal */
            multiplicity_ordinal: number;
            /**
             * Occurrence Id
             * Format: uuid
             */
            occurrence_id: string;
            /**
             * Representation Id
             * Format: uuid
             */
            representation_id: string;
            /** Source Date */
            source_date: string | null;
            /** Source Date Original */
            source_date_original: unknown;
            /** Source Date Status */
            source_date_status: string;
        };
        /** ProcessMovementsResponse */
        ProcessMovementsResponse: {
            /** Diagnostics */
            diagnostics: components["schemas"]["MovementDiagnosticResponse"][];
            /** Items */
            items: components["schemas"]["ProcessMovementResponse"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /**
             * Process Id
             * Format: uuid
             */
            process_id: string;
            /** Total */
            total: number;
        };
        /** ProcessRepresentationResponse */
        ProcessRepresentationResponse: {
            /** Class Code */
            class_code: string | null;
            /** Class Name */
            class_name: string | null;
            /** Court Unit Code */
            court_unit_code: string | null;
            /** Court Unit Name */
            court_unit_name: string | null;
            /** Grau */
            grau: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Observed At */
            last_observed_at: string | null;
            latest_collection: components["schemas"]["LatestCollectionResponse"] | null;
            /** Latest Version Id */
            latest_version_id: string | null;
            movement_diagnostic: components["schemas"]["MovementDiagnosticResponse"];
            /**
             * Process Id
             * Format: uuid
             */
            process_id: string;
            /** Source */
            source: string;
            /** Source Filed At */
            source_filed_at: string | null;
            /** Source Filed At Original */
            source_filed_at_original: string | null;
            /** Source Filed At Timezone Ambiguous */
            source_filed_at_timezone_ambiguous: boolean;
            /** Source Id */
            source_id: string;
            /** Source Updated At */
            source_updated_at: string | null;
            /** Source Updated At Original */
            source_updated_at_original: string | null;
            /** Source Updated At Timezone Ambiguous */
            source_updated_at_timezone_ambiguous: boolean;
            /** Tribunal */
            tribunal: string;
        };
        /** ProcessSummaryResponse */
        ProcessSummaryResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            latest_collection: components["schemas"]["LatestCollectionResponse"] | null;
            /** Latest Observed At */
            latest_observed_at: string | null;
            /** Numero Cnj */
            numero_cnj: string;
            /** Representation Count */
            representation_count: number;
        };
        /** ReadyResponse */
        ReadyResponse: {
            /** Checks */
            checks: {
                [key: string]: "ok" | "pending" | "unavailable" | "unknown";
            };
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
        };
        /** RefreshNumberCriteria */
        RefreshNumberCriteria: {
            /**
             * Hit Budget
             * @default 2000
             */
            hit_budget: number;
            /**
             * Page Size
             * @default 100
             */
            page_size: number;
            /** Process Number */
            process_number: string;
        };
        /** RefreshNumberJobRequest */
        RefreshNumberJobRequest: {
            criteria: components["schemas"]["RefreshNumberCriteria"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "refresh_number";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_environment_api_v1_environment_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentResponse"];
                };
            };
            /** @description Recurso não encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflito de estado ou capacidade indisponível. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Entrada inválida. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Banco de dados indisponível. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    live_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveResponse"];
                };
            };
        };
    };
    ready_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description Database or Alembic revision is not ready. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_jobs_api_v1_jobs_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                status?: string | null;
                kind?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginationResponse_JobSummaryResponse_"];
                };
            };
            /** @description Recurso não encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflito de estado ou capacidade indisponível. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Entrada inválida. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Banco de dados indisponível. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_job_api_v1_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscoveryJobRequest"] | components["schemas"]["RefreshNumberJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCreatedResponse"];
                };
            };
            /** @description Recurso não encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflito de estado ou capacidade indisponível. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Entrada inválida. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Banco de dados indisponível. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetailResponse"];
                };
            };
            /** @description Recurso não encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflito de estado ou capacidade indisponível. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Entrada inválida. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Banco de dados indisponível. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cancel_job_api_v1_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCommandResponse"];
                };
            };
            /** @description Recurso não encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflito de estado ou capacidade indisponível. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Entrada inválida. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Banco de dados indisponível. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    continue_job_api_v1_jobs__job_id__continue_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCommandResponse"];
                };
            };
            /** @description Recurso não encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflito de estado ou capacidade indisponível. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Entrada inválida. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Banco de dados indisponível. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    restart_scan_api_v1_jobs__job_id__restart_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCommandResponse"];
                };
            };
            /** @description Recurso não encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflito de estado ou capacidade indisponível. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Entrada inválida. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Banco de dados indisponível. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    resume_job_api_v1_jobs__job_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCommandResponse"];
                };
            };
            /** @description Recurso não encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflito de estado ou capacidade indisponível. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Entrada inválida. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Banco de dados indisponível. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_presets_api_v1_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetsResponse"];
                };
            };
            /** @description Recurso não encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflito de estado ou capacidade indisponível. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Entrada inválida. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Banco de dados indisponível. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_processes_api_v1_processes_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                process_number?: string | null;
                subject?: string | null;
                class?: string | null;
                court_unit?: string | null;
                collection_id?: string | null;
                preset_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginationResponse_ProcessSummaryResponse_"];
                };
            };
            /** @description Recurso não encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflito de estado ou capacidade indisponível. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Entrada inválida. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Banco de dados indisponível. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_process_api_v1_processes__process_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                process_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessDetailResponse"];
                };
            };
            /** @description Recurso não encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflito de estado ou capacidade indisponível. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Entrada inválida. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Banco de dados indisponível. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_movements_api_v1_processes__process_id__movements_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                process_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessMovementsResponse"];
                };
            };
            /** @description Recurso não encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflito de estado ou capacidade indisponível. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Entrada inválida. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Banco de dados indisponível. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_representations_api_v1_processes__process_id__representations_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                process_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginationResponse_ProcessRepresentationResponse_"];
                };
            };
            /** @description Recurso não encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflito de estado ou capacidade indisponível. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Entrada inválida. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Banco de dados indisponível. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
